services:
    postgres:
        container_name: service-postgres
        image: postgres:17
        environment: &db_env
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
          interval: 10s
          retries: 5


    service_template-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          <<: *db_env
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /service_template/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/service_template:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /service_template
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          postgres:
            condition: service_healthy
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
